version: '3'
services:
  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: audiospheredb
    ports:
      - 3306:3306
  node:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db", "3306", "--", "npm", "start"]
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=audiospheredb